/**
 * COO hangout engine.
 *
 * No new agent is created anywhere: the residents of the town are the users'
 * real Aicoo COOs. A hangout is N rounds where
 *
 *   1. the player's OWN COO composes its turn (`/v1/chat`, non-streaming) —
 *      speaking as itself, under its own identity and policy files, and
 *   2. the turn is delivered over Aicoo's agent-to-agent messaging
 *      (`/v1/agent/message` → `<partner>_coo`), whose reply is generated by
 *      the partner's COO under the partner's own permissions.
 *
 * The app adds nothing to the messaging path — no custom gate, no persona.
 * Per-perspective memory: the transcript is appended to the player's
 * DatingWorld/dyads/<partner> note with a snapshot after every hangout.
 */
import {
  cooChat,
  getNote,
  listNotes,
  listSnapshots,
  messageAgent,
  saveSnapshot,
  upsertNote,
} from './aicoo.js';

const DYADS_FOLDER = 'DatingWorld/dyads';

export interface HangoutTurn {
  speaker: 'your-coo' | 'partner-coo';
  text: string;
}

export interface HangoutResult {
  partner: string;
  turns: HangoutTurn[];
  dyadNoteId: number;
}

export async function listDyads(bearer: string): Promise<Array<{ id: number; partner: string }>> {
  const notes = await listNotes(bearer, 'dyads');
  return notes.map((n) => ({ id: n.id, partner: n.title }));
}

export async function getDyad(
  bearer: string,
  partner: string
): Promise<{ content: string; snapshots: unknown } | null> {
  const note = (await listNotes(bearer, 'dyads')).find((n) => n.title === partner);
  if (!note) return null;
  const [content, snapshots] = await Promise.all([
    getNote(bearer, note.id),
    listSnapshots(bearer, note.id),
  ]);
  return { content, snapshots };
}

/** Strip chat-UI protocol artifacts (e.g. <suggestions> blocks) that the
 *  COO emits for its own chat client — they are not part of what it says. */
function cleanComposedTurn(text: string): string {
  return text
    .replace(/<suggestions>[\s\S]*?<\/suggestions>/gi, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function composePrompt(partner: string, partnerSaid: string | null, topic?: string): string {
  const setting = `You are hanging out with ${partner}'s COO in Aicoo Dating World — a shared town where COOs socialize on behalf of their humans.`;
  const style =
    'Speak as yourself, in your own voice, under your own policies. Keep it to 2–4 sentences, warm and genuinely curious. Do not use any tools; just reply with what you would say.';
  if (partnerSaid === null) {
    return `${setting} Open the conversation${topic ? ` — suggested topic: ${topic}` : ''}. ${style}`;
  }
  return `${setting} They just said: "${partnerSaid.slice(0, 800)}". Continue the conversation. ${style}`;
}

/**
 * Run one hangout of `rounds` exchanges. Both voices are real COOs; this
 * function only ferries messages and records the player's perspective.
 */
export async function runHangout(
  bearer: string,
  partnerUsername: string,
  rounds = 1,
  topic?: string
): Promise<HangoutResult> {
  const turns: HangoutTurn[] = [];
  let threadId: string | undefined;
  let partnerSaid: string | null = null;

  for (let round = 0; round < rounds; round++) {
    const composed = await cooChat(
      bearer,
      composePrompt(partnerUsername, partnerSaid, topic),
      threadId
    );
    threadId = composed.conversationId;
    const myLine = cleanComposedTurn(composed.response);
    turns.push({ speaker: 'your-coo', text: myLine });

    const reply = await messageAgent(bearer, `${partnerUsername}_coo`, myLine, 'query');
    partnerSaid = reply.response ?? '[no reply]';
    turns.push({ speaker: 'partner-coo', text: partnerSaid });
  }

  const existing =
    (await getDyad(bearer, partnerUsername))?.content ?? `Dyad: ${partnerUsername}\n`;
  const entry =
    `\nHangout — ${new Date().toISOString()}\n` +
    turns.map((t) => `${t.speaker}: ${t.text.replace(/\n/g, ' ').slice(0, 900)}`).join('\n') +
    '\n';

  const dyadNoteId = await upsertNote(bearer, DYADS_FOLDER, partnerUsername, existing + entry);
  await saveSnapshot(bearer, dyadNoteId, `hangout:${partnerUsername}`);

  return { partner: partnerUsername, turns, dyadNoteId };
}
